### ISSUE TITLE
"Classy" (Flat theme with Serif and warm colors)

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/pm-theme#12]
A "Shaken not stirred" kinda theme. Copy paste into the custom theme box:

<img src="http://i.imgur.com/A1Y7iWm.png" width="100%" />

```css
/* First load the theme. */
@import url("https://austindelamar.com/pm-theme/themes/pm-flat-theme.css");

/* Now override colors. */
:root {
    --theme1: #6d5e4e;
    --theme2: #68635e;
    --theme4: #bbbebf;
    --theme5: #82807a;
    --theme6: #afa067;
}

/* Set fonts */
body,h1,h2,h3,h4,h5,h6,p,span,b,strong,em,th,td{
    font-family: "Georgia", Times, serif !important;
}
/* Button is by itself or some icons will break. */
button {
    font-family: "Georgia", Times, serif;
}
```
