### ISSUE TITLE
"Typewriter" (Flat theme with Serif and grey colors)

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/pm-theme#13]
A sophisticated theme. Copy paste into the custom theme box:

<img src="http://i.imgur.com/Ftvkphf.png" width="100%" />

```css
/* First load the theme. */
@import url("https://austindelamar.com/pm-theme/themes/pm-flat-theme.css");

/* Now override colors. */
:root {
    --theme1: #4f4f4f;
    --theme6: #777777;
}

/* Set fonts */
body,h1,h2,h3,h4,h5,h6,p,span,b,strong,em,th,td{
    font-family: "Georgia", Times, serif !important;
}
/* Button is by itself or some icons will break. */
button {
    font-family: "Georgia", Times, serif;
}
```
