### ISSUE TITLE
Search Modal background color is uneven

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/pm-theme#18]
## What is the Problem?

Search Modal background color is uneven.

## Do you know what would fix it?

```css
// flat-theme, gm-theme
.searchForm-advanced-container, .searchForm-advanced-main, .searchForm-advanced-wrapper {
  background-color: var(--theme3);
}
// dark-theme
.searchForm-advanced-container, .searchForm-advanced-main, .searchForm-advanced-wrapper {
  background-color: var(--theme7);
}
```
