### ISSUE TITLE
black text for conversation

### ISSUE THREAD

**Issue by log69** [amdelamar/pm-theme#27]
## Your Environment
 * Theme used: Default (Proton)
 * Browser name and version: Firefox 59 x64
 * OS/Device version: Linux / Ubuntu 16 x64

## What is the Problem?
Most of the time the conversation texts are gray and so they are hard to read. I want them black all the time to get full contrast. Could you help me with a short CSS code to make it? Thanks for your work.

**Comment by amdelamar** [comment]
I think this should do it.

```css
/* Message body text */
#conversation-view .message {
  color: var(--black) !important;
}

/* Message header details */
#conversation-view .message .frame {
  color: var(--black) !important;
}
```

**Comment by log69** [comment]
It's doesn't help. The email body of some messages still stay gray. Could it have anything to do with HTML formatted mails that are not plain texts? Though plain texts come in gray as well.

**Comment by amdelamar** [comment]
It works for me. On plaintext and some HTML simple emails. But not complex HTML like newsletters for example.

How are you pasting the CSS? Right into the custom theme box and after the `@import` statement correct?

```css
/* Copy this line into ProtonMail's custom theme box: */
@import url("https://austindelamar.com/pm-theme/themes/pm-flat-theme.min.css");

#conversation-view .message {
  color: var(--black) !important;
}
#conversation-view .message .frame {
  color: var(--black) !important;
}
```
