### ISSUE TITLE
Dark Theme: Mail contents and compose windows are still light

### ISSUE THREAD

**Issue by RoxKilly** [amdelamar/pm-theme#46]
## Your Environment
 * Theme used: Dark
 * Browser name and version: Firefox 64.0 64-bit
 * OS/Device version: Windows 10

## Describe the Problem

the mail contents window and the compose window still have white background.  Is this because of a limitation? The [Dark Reader](https://github.com/darkreader/darkreader) addon is able to darken those backgrounds but I don't know whether it's because that has more access as an extension.

**Comment by amdelamar** [comment]
I've tried in the past, but it doesn't work very well.

HTML emails come with their own CSS of colors/background/images. Darkening that would be very difficult and wouldn't be consistent.

Plaintext emails could be darkened, easily.

I made a decision to not alter plaintext emails because it was jarring to view darkened emails mixed with regular white background HTML emails. Hurt my eyes a bit.

**Comment by amdelamar** [comment]
If you'd like some CSS to darken plaintext emails you can try adding this:

```css
#pm_composer .composer .fill {
    background: var(--theme3) !important;
}
body {
    color: white !important;
}

#conversation-view .message .frame {
    color: var(--white) !important;
    background-color: var(--theme3) !important;
}
```
